import type {
  OrgType,
  BudgetRange,
  GeographicReach,
  ActivityArea,
  Demographic,
  County,
  OrgSetting,
  GrantWritingCapacity,
  ProfileSection,
  OrgProfileFormData,
  ProfileSectionMeta,
} from '@/types/org'

export const ORG_TYPES: Record<OrgType, string> = {
  clg: 'Company Limited by Guarantee (CLG)',
  cic: 'Community Interest Company (CIC)',
  unincorporated: 'Unincorporated Association',
  'charitable-trust': 'Charitable Trust',
  cooperative: 'Co-operative Society',
  'registered-charity': 'Registered Charity',
  'social-enterprise': 'Social Enterprise',
  'friendly-society': 'Friendly Society',
  other: 'Other',
}

export const COUNTIES: Record<County, string> = {
  carlow: 'Carlow',
  cavan: 'Cavan',
  clare: 'Clare',
  cork: 'Cork',
  donegal: 'Donegal',
  dublin: 'Dublin',
  galway: 'Galway',
  kerry: 'Kerry',
  kildare: 'Kildare',
  kilkenny: 'Kilkenny',
  laois: 'Laois',
  leitrim: 'Leitrim',
  limerick: 'Limerick',
  longford: 'Longford',
  louth: 'Louth',
  mayo: 'Mayo',
  meath: 'Meath',
  monaghan: 'Monaghan',
  offaly: 'Offaly',
  roscommon: 'Roscommon',
  sligo: 'Sligo',
  tipperary: 'Tipperary',
  waterford: 'Waterford',
  westmeath: 'Westmeath',
  wexford: 'Wexford',
  wicklow: 'Wicklow',
}

export const ACTIVITY_AREAS: Record<ActivityArea, string> = {
  'arts-culture': 'Arts & Culture',
  'sports-recreation': 'Sports & Recreation',
  'community-development': 'Community Development',
  'education-training': 'Education & Training',
  'health-wellbeing': 'Health & Wellbeing',
  environment: 'Environment',
  'climate-action': 'Climate Action',
  'just-transition': 'Just Transition',
  'heritage-conservation': 'Heritage & Conservation',
  'coastal-marine': 'Coastal & Marine',
  dsgbv: 'Domestic, Sexual & Gender-Based Violence',
  'lgbtiq-plus': 'LGBTIQ+',
  disability: 'Disability Services',
  'mental-health': 'Mental Health',
  'children-young-people': 'Children & Young People',
  'older-people': 'Older People',
  'housing-homelessness': 'Housing & Homelessness',
  'social-inclusion': 'Social Inclusion',
  'rural-development': 'Rural Development',
  'urban-regeneration': 'Urban Regeneration',
  volunteering: 'Volunteering & Civic Engagement',
  'international-development': 'International Development',
  'animal-welfare': 'Animal Welfare',
  'food-agriculture': 'Food & Agriculture',
  'technology-digital': 'Technology & Digital',
  tourism: 'Tourism & Hospitality',
  'employment-enterprise': 'Employment & Enterprise',
  'irish-language': 'Irish Language & Culture (Gaeilge)',
}

export const DEMOGRAPHICS: Record<Demographic, string> = {
  'children-0-11': 'Children (0–11)',
  'young-people-12-24': 'Young People (12–24)',
  'older-people-65-plus': 'Older People (65+)',
  'people-with-disabilities': 'People with Disabilities',
  'experiencing-homelessness': 'People Experiencing Homelessness',
  'migrants-refugees': 'Migrants & Refugees',
  'traveller-roma': 'Traveller & Roma Community',
  'lgbtiq-plus': 'LGBTIQ+ Community',
  'women-girls': 'Women & Girls',
  'men-boys': 'Men & Boys',
  'lone-parents': 'Lone Parents',
  'long-term-unemployed': 'Long-term Unemployed',
  'people-in-recovery': 'People in Recovery',
  'rural-communities': 'Rural Communities',
  'coastal-communities': 'Coastal Communities',
  'general-public': 'General Public',
}

export const BUDGET_RANGES: Record<BudgetRange, string> = {
  'under-10k': 'Under €10,000',
  '10k-50k': '€10,000 – €50,000',
  '50k-100k': '€50,000 – €100,000',
  '100k-250k': '€100,000 – €250,000',
  '250k-500k': '€250,000 – €500,000',
  '500k-1m': '€500,000 – €1,000,000',
  'over-1m': 'Over €1,000,000',
}

export const GEO_REACH_LABELS: Record<GeographicReach, string> = {
  local: 'Local (town / parish)',
  county: 'County-wide',
  regional: 'Regional (multiple counties)',
  national: 'National',
  international: 'International',
}

export const ORG_SETTINGS: Record<OrgSetting, string> = {
  urban: 'Urban',
  suburban: 'Suburban',
  rural: 'Rural',
  mixed: 'Mixed',
}

export const GRANT_WRITING_CAPACITY: Record<GrantWritingCapacity, string> = {
  none: 'No experience yet',
  some: 'Some experience',
  experienced: 'Experienced',
}

export const PROFILE_SECTIONS: ProfileSectionMeta[] = [
  {
    id: 'identity' as ProfileSection,
    label: 'Identity',
    description: 'Name, legal status, and purpose',
    icon: 'Building2',
  },
  {
    id: 'location' as ProfileSection,
    label: 'Location',
    description: 'Address, county, and setting',
    icon: 'MapPin',
  },
  {
    id: 'contact' as ProfileSection,
    label: 'Contact',
    description: 'Primary contact and website',
    icon: 'Mail',
  },
  {
    id: 'capacity' as ProfileSection,
    label: 'Capacity',
    description: 'Staff, volunteers, and turnover',
    icon: 'Users',
  },
  {
    id: 'activities' as ProfileSection,
    label: 'Activities',
    description: 'Work areas and beneficiaries',
    icon: 'Target',
  },
  {
    id: 'grant-experience' as ProfileSection,
    label: 'Grant Experience',
    description: 'Funding history and capacity',
    icon: 'FileText',
  },
]

export const DEFAULT_FORM_DATA: OrgProfileFormData = {
  name: '',
  legalName: '',
  orgType: 'clg',
  charityNumber: '',
  companyNumber: '',
  taxExemptionRef: '',
  yearFounded: new Date().getFullYear(),
  description: '',
  mission: '',
  website: '',
  addressLine1: '',
  addressLine2: '',
  town: '',
  county: 'dublin',
  eircode: '',
  setting: 'urban',
  geographicReach: 'local',
  contactName: '',
  contactRole: '',
  contactEmail: '',
  contactPhone: '',
  staffCount: 0,
  volunteerCount: 0,
  budgetRange: '10k-50k',
  activityAreas: [],
  targetDemographics: [],
  hasGrantExperience: false,
  previousGrantsDetail: '',
  largestGrantReceived: '',
  grantWritingCapacity: 'none',
}

export const SECTION_ORDER: ProfileSection[] = [
  'identity',
  'location',
  'contact',
  'capacity',
  'activities',
  'grant-experience',
]
